# Generated by Django 6.0.1 on 2026-01-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidate',
            table='candidates',
        ),
        migrations.AlterModelTable(
            name='interview',
            table='interviews',
        ),
    ]
