# Generated by Django 6.0.1 on 2026-01-26 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_table_alter_interview_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Associated user account for role-based status viewing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='previous_experience',
            field=models.JSONField(blank=True, default=dict, help_text='Stores experience data in key-value pairs (Institute: Position).'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('scheduled', 'Interview Scheduled'), ('passed', 'Passed (1st Round)'), ('second_interview', 'Second Interview Scheduled'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='applied', max_length=50),
        ),
    ]
