# Generated by Django 6.0.1 on 2026-01-26 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_user_alter_candidate_previous_experience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='notes',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='previous_experience',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('scheduled', 'Interview Scheduled'), ('passed', 'Passed (1st Round)'), ('rejected', 'Rejected'), ('second_round', 'Second Interview Scheduled'), ('hired', 'Hired')], default='applied', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AlterModelTable(
            name='candidate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='interview',
            table=None,
        ),
    ]
