# Generated by Django 6.0.1 on 2026-01-27 21:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_alter_candidate_options_remove_candidate_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-interview_date'], 'verbose_name': 'Interview', 'verbose_name_plural': 'Interviews'},
        ),
        migrations.AddField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='interview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interview',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Interview Notes'),
        ),
        migrations.AddField(
            model_name='interview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)], verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Years of Experience'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='previous_experience',
            field=models.JSONField(blank=True, default=dict, help_text="JSON structure: {'institute_name': 'position'}", verbose_name='Previous Experience'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('scheduled', 'Interview Scheduled'), ('passed', 'Passed (1st Round)'), ('rejected', 'Rejected'), ('second_round', 'Second Interview Scheduled'), ('hired', 'Hired')], db_index=True, default='applied', max_length=50, verbose_name='Application Status'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Associated user account for candidate portal access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interview',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='candidates.candidate', verbose_name='Candidate'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_date',
            field=models.DateTimeField(db_index=True, verbose_name='Interview Date & Time'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('1st', 'First Interview'), ('2nd', 'Second Interview')], default='1st', max_length=10, verbose_name='Interview Type'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='upcoming', max_length=20, verbose_name='Interview Status'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['status', '-created_at'], name='candidates__status_2e6956_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email'], name='candidates__email_188e48_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['candidate', 'interview_date'], name='candidates__candida_2d2ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['status', 'interview_date'], name='candidates__status_aaee31_idx'),
        ),
        migrations.AddConstraint(
            model_name='interview',
            constraint=models.UniqueConstraint(fields=('candidate', 'interview_date', 'interview_type'), name='unique_candidate_interview'),
        ),
    ]
